slam_toolbox:
  ros__parameters:
    base_frame: base_link
    odom_frame: odom
    scan_topic: /scan
    map_frame: map
    resolution: 0.05
    # How far robot must move before adding a new scan node
    minimum_travel_distance: 0.25   # metres
    minimum_travel_heading: 0.3    # radians

    # How far back in time to match scans
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 10.0
    map_update_interval: 3.0
    mode: mapping
