services:
  mobrob_cv1:
    build:
      context: .
      dockerfile: dockerfiles/CVDockerfile
    pull_policy: build
    network_mode: host
    stdin_open: true
    tty: true
    privileged: true
    volumes:
      - /dev:/dev
      - /home/team8/Documents:/opt/ros2ws/img

  mobrob_aria1:
    build:
      context: .
      dockerfile: dockerfiles/ariaDockerfile
    pull_policy: build
    logging:
      driver: "none"
    network_mode: host
    stdin_open: true
    tty: true
    privileged: true
    volumes:
      - /dev:/dev

  mobrob_ctrl1:
    build:
      context: .
      dockerfile: dockerfiles/ctrlDockerfile
    pull_policy: build
    network_mode: host
    stdin_open: true
    tty: true
    privileged: true
    volumes:
      - /dev:/dev

  mobrob_global_controller1:
    build:
      context: .
      dockerfile: dockerfiles/globalcontrollerDockerfile
    pull_policy: build
    network_mode: host
    stdin_open: true
    tty: true
    privileged: true
    restart: unless-stopped
    volumes:
      - /dev:/dev
      - /home/team8/Documents:/root/costmap_exports

  mobrob_ekf1:
    build:
      context: .
      dockerfile: dockerfiles/Sensors/EKFDockerfile
    pull_policy: build
    network_mode: host
    stdin_open: true
    tty: true
    privileged: true
    volumes:
      - /dev:/dev


  mobrob_sick1:
    build:
      context: .
      dockerfile: dockerfiles/Sensors/SICKScanDockerfile
    pull_policy: build
    network_mode: host
    stdin_open: true
    tty: true
    privileged: true
    volumes:
      - /dev:/dev

  mobrob_nav4:
    build:
      context: .
      dockerfile: dockerfiles/nav2Dockerfile
    pull_policy: build
    network_mode: host
    stdin_open: true
    tty: true
    privileged: true
    volumes:
      - /dev:/dev
   
  mobrob_image_publisher1:
   build:
     context: .
     dockerfile: dockerfiles/image_publisherDockerfile
   pull_policy: build
   network_mode: host
   stdin_open: true
   tty: true
   privileged: true
   volumes: 
     - /dev:/dev
     - /dev/bus/usb:/dev/bus/usb
   device_cgroup_rules:
     - 'c 189:* rmw'
  
  mobrob_greek1:
    build:
      context: .
      dockerfile: dockerfiles/greekDockerfile
    pull_policy: build
    network_mode: host
    stdin_open: true
    tty: true
    privileged: true
    volumes:
      - /dev:/dev

  mobrob_gui1:
    build:
      context: .
      dockerfile: dockerfiles/guiDockerfile
    pull_policy: build
    network_mode: host
    stdin_open: true
    tty: true
    privileged: true
    volumes:
      - /dev:/dev

  # mobrob_compvis1:
  #   build:
  #     context: .
  #     dockerfile: dockerfiles/CompVisDockerfile
  #   pull_policy: build
  #   network_mode: host
  #   stdin_open: true
  #   tty: true
  #   privileged: true
  #   volumes:
  #     - /dev:/dev  
 
