services:
  mobrob_cv:
    build:
      context: .
      dockerfile: dockerfiles/CVDockerfile
    pull_policy: build
    network_mode: host
    stdin_open: true
    tty: true
    privileged: true
    volumes:
      - /dev:/dev
      - /home/team8/Documents:/opt/ros2ws/img

  mobrob_sens:
    build:
      context: .
      dockerfile: dockerfiles/sensDockerfile
    pull_policy: build
    logging:
      driver: "none"
    network_mode: host
    stdin_open: true
    tty: true
    privileged: true
    volumes:
      - /dev:/dev

  mobrob_aria:
    build:
      context: .
      dockerfile: dockerfiles/ariaDockerfile
    pull_policy: build
    logging:
      driver: "none"
    network_mode: host
    stdin_open: true
    tty: true
    privileged: true
    volumes:
      - /dev:/dev

  mobrob_ctrl:
    build:
      context: .
      dockerfile: dockerfiles/ctrlDockerfile
    pull_policy: build
    network_mode: host
    stdin_open: true
    tty: true
    privileged: true
    volumes:
      - /dev:/dev

  mobrob_basic_drive:
    build:
      context: .
      dockerfile: dockerfiles/basicdriveDockerfile
    pull_policy: build
    network_mode: host
    stdin_open: true
    tty: true
    privileged: true
    volumes:
      - /dev:/dev

  mobrob_global_controller:
    build:
      context: .
      dockerfile: dockerfiles/globalcontrollerDockerfile
    pull_policy: build
    network_mode: host
    stdin_open: true
    tty: true
    privileged: true
    restart: unless-stopped
    volumes:
      - /dev:/dev

  mobrob_ekf:
    build:
      context: .
      dockerfile: dockerfiles/Sensors/EKFDockerfile
    pull_policy: build
    network_mode: host
    stdin_open: true
    tty: true
    privileged: true
    volumes:
      - /dev:/dev

  mobrob_imu:
    build:
      context: .
      dockerfile: dockerfiles/Sensors/IMUDockerfile
    pull_policy: build
    network_mode: host
    stdin_open: true
    tty: true
    privileged: true
    volumes:
      - /dev:/dev

  mobrob_sick:
    build:
      context: .
      dockerfile: dockerfiles/Sensors/SICKScanDockerfile
    pull_policy: build
    network_mode: host
    stdin_open: true
    tty: true
    privileged: true
    volumes:
      - /dev:/dev

  mobrob_nav3:
    build:
      context: .
      dockerfile: dockerfiles/nav2Dockerfile
    pull_policy: build
    network_mode: host
    stdin_open: true
    tty: true
    privileged: true
    volumes:
      - /dev:/dev

  mobrob_gui:
    build:
      context: .
      dockerfile: dockerfiles/guiDockerfile
    pull_policy: build
    network_mode: host
    stdin_open: true
    tty: true
    privileged: true
    volumes:
      - /dev:/dev

  mobrob_compvis:
    build:
      context: .
      dockerfile: dockerfiles/CompVisDockerfile
    pull_policy: build
    network_mode: host
    stdin_open: true
    tty: true
    privileged: true
    volumes:
      - /dev:/dev  
 
