services:
  mobrob_aria2:
    build:
      context: .
      dockerfile: dockerfiles/ariaDockerfile
    pull_policy: build
    logging:
      driver: "none"
    network_mode: host
    stdin_open: true
    tty: true
    privileged: true
    volumes:
      - /dev:/dev

  mobrob_ctrl2:
    build:
      context: .
      dockerfile: dockerfiles/ctrlDockerfile
    pull_policy: build
    network_mode: host
    stdin_open: true
    tty: true
    privileged: true
    volumes:
      - /dev:/dev

  mobrob_cv2:
    build:
      context: .
      dockerfile: dockerfiles/CVDockerfile
    pull_policy: build
    network_mode: host
    stdin_open: true
    tty: true
    privileged: true
    volumes:
      - /dev:/dev
      - /home/team8/Documents:/opt/ros2ws/src/cv/img

  mobrob_global_controller2:
    build:
      context: .
      dockerfile: dockerfiles/globalcontrollerDockerfile
    pull_policy: build
    network_mode: host
    stdin_open: true
    tty: true
    privileged: true 
    restart: unless-stopped
    volumes:
      - /dev:/dev

  mobrob_ekf2:
    build:
      context: .
      dockerfile: dockerfiles/Sensors/EKFDockerfile
    pull_policy: build
    network_mode: host
    stdin_open: true
    tty: true
    privileged: true
    volumes:
      - /dev:/dev

  mobrob_imu2:
    build:
      context: .
      dockerfile: dockerfiles/Sensors/IMUDockerfile
    pull_policy: build
    network_mode: host
    stdin_open: true
    tty: true
    privileged: true
    volumes:
      - /dev:/dev

  mobrob_sick2:
    build:
      context: .
      dockerfile: dockerfiles/Sensors/SICKScanDockerfile
    pull_policy: build
    network_mode: host
    stdin_open: true
    tty: true
    privileged: true
    volumes:
      - /dev:/dev
      
  mobrob_nav3:
    build:
      context: .
      dockerfile: dockerfiles/nav2Dockerfile
    pull_policy: build
    network_mode: host
    stdin_open: true
    tty: true
    privileged: true
    volumes:
      - /dev:/dev
   
  # mobrob_image_publisher:
  #  build:
  #    context: .
  #    dockerfile: dockerfiles/image_publisherDockerfile
  #  pull_policy: build
  #  network_mode: host
  #  stdin_open: true
  #  tty: true
  #  privileged: true
  #  volumes:
  #    - /dev:/dev
  #    - /dev/bus/usb:/dev/bus/usb
  #  device_cgroup_rules:
  #    - 'c 189:* rmw'
      
      
  # #  mobrob_greek:
  #   build:
  #     context: .
  #     dockerfile: dockerfiles/greekDockerfile
  #   pull_policy: build
  #   network_mode: host
  #   stdin_open: true
  #   tty: true
  #   privileged: true
  #   volumes:
  #     - /dev:/dev
  
  mobrob_gui2:
    build:
      context: .
      dockerfile: dockerfiles/guiDockerfile
    pull_policy: build
    network_mode: host
    stdin_open: true
    tty: true
    privileged: true
    volumes:
      - /dev:/dev