services:
  mobrob:
    build:
      context: ..
      dockerfile: dockerfiles/CompVisDockerfile
    pull_policy: build
    command: /bin/bash
    network_mode: host
    stdin_open: true
    tty: true
    privileged: true
    volumes:
      - /dev:/dev